---

- name: Create /etc/php5/cli/conf.d
  file: path=/etc/php5/cli/conf.d state=directory mode=0755 recurse=yes
  become: yes

- name: Create php.ini
  template: src=php.ini dest=/etc/php5/cli/php.ini mode=0644
  become: yes

- name: Apt hold
  shell: echo "php5-cli hold" | dpkg --set-selections
  become: yes
