---
- name: Download source code
  get_url: url=http://pecl.php.net/get/igbinary-{{ ext_igbinary_version }}.tgz dest=/tmp/igbinary-{{ ext_igbinary_version }}.tgz

- name: Extract archive
  command: chdir=/tmp/ tar xfz igbinary-{{ ext_igbinary_version }}.tgz creates=/tmp/igbinary-{{ ext_igbinary_version }}

- name: Phpize
  shell: phpize > /dev/null chdir=/tmp/igbinary-{{ ext_igbinary_version }}

- name: Configure
  shell: ./configure > /dev/null chdir=/tmp/igbinary-{{ ext_igbinary_version }}

- name: Make
  shell: make > /dev/null chdir=/tmp/igbinary-{{ ext_igbinary_version }}

- name: Install
  shell: make install > /dev/null chdir=/tmp/igbinary-{{ ext_igbinary_version }}
  become: yes