---
- name: Install libmagickwand-dev
  apt: name=libmagickwand-dev state=present update_cache=yes cache_valid_time=3600
  become: yes

- name: Download source code
  get_url: url=http://pecl.php.net/get/imagick-{{ ext_imagick_version }}.tgz dest=/tmp/imagick-{{ ext_imagick_version }}.tgz

- name: Extract archive
  command: chdir=/tmp/ tar xfz imagick-{{ ext_imagick_version }}.tgz creates=/tmp/imagick-{{ ext_imagick_version }}

- name: Phpize
  shell: chdir=/tmp/imagick-{{ ext_imagick_version }} phpize > /dev/null

- name: Configure
  shell: chdir=/tmp/imagick-{{ ext_imagick_version }} ./configure --enable-memcached-igbinary --disable-memcached-sasl > /dev/null

- name: Make
  shell: chdir=/tmp/imagick-{{ ext_imagick_version }} make > /dev/null

- name: Install
  shell: chdir=/tmp/imagick-{{ ext_imagick_version }} make install > /dev/null
  become: yes