---

- name: Get php version
  command: php --version
  register: php_current
  ignore_errors: yes

- name: Install php-cli
  include: php-cli.yml
  when: php_current.rc != 0 or php_current.stdout.find('PHP {{ php_version }} (cli)') == -1

- name: Install ext-igbinary
  include: ext-igbinary.yml

- name: Install ext-apcu
  include: ext-apcu.yml

- name: Install ext-memcached
  include: ext-memcached.yml

- name: Install ext-imagick
  include: ext-imagick.yml

- name: Install ext-redis
  include: ext-redis.yml