---

- name: Get php version
  command: php --version
  register: php5cli_current
  ignore_errors: yes

- set_fact: php5cli_real_version="{{ php5cli_version | regex_replace('-\\d+$', '') }}"

- name: Install php-cli
  include: php-cli.yml
  when: php5cli_current.rc != 0 or php5cli_current.stdout.find("PHP {{ php5cli_real_version }} (cli)") == -1

- include: config.yml

- include: ext-apcu.yml

- include: ext-imagick.yml

- include: ext-igbinary.yml

- include: ext-memcached.yml

- include: ext-redis.yml