---

- name: Get php version
  command: php --version
  register: php_current
  ignore_errors: yes

- set_fact: php_real_version="{{ php_version | regex_replace('-\\d+$', '') }}"

- name: Install php-cli
  include: php-cli.yml
  when: php_current.rc != 0 or php_current.stdout.find("PHP {{ php_real_version }} (cli)") == -1

- include: ext-apcu.yml

- include: ext-imagick.yml

- include: ext-igbinary.yml

- include: ext-memcached.yml

- include: ext-redis.yml