---
- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - make
    - gcc
    - g++
    - libicu-dev
    - libssl-dev
    - libxml2-dev
    - libcurl4-openssl-dev
    - libjpeg-dev
    - libvpx-dev
    - libpng12-dev
    - libfreetype6-dev
    - libc-client2007e-dev
    - libkrb5-dev
    - libmcrypt-dev
    - libxslt1-dev
    - libbz2-dev
    - automake
    - autoconf
    - pkg-config
  become: yes

- name: Download source code
  get_url: url=http://phpmirror.oam.rocks/php-{{ php_version }}.tar.gz dest=/tmp/php-{{ php_version }}.tar.gz

- name: Extract archive
  command: chdir=/tmp/ tar xfz php-{{ php_version }}.tar.gz creates=/tmp/php-{{ php_version }}

- name: Make clean
  command: chdir=/tmp/php-{{ php_version }} make clean
  ignore_errors: yes

- name: Configure
  command: >
    ./configure
    --prefix=/usr
    --sysconfdir=/etc
    --localstatedir=/var
    --disable-cgi
    --with-config-file-path=/etc/php5/cli
    --with-config-file-scan-dir=/etc/php5/cli/conf.d
    --with-libxml-dir
    --with-openssl
    --with-pcre-regex
    --with-zlib
    --with-bz2
    --enable-calendar
    --with-curl
    --enable-exif
    --enable-ftp
    --with-gd
    --with-vpx-dir
    --with-jpeg-dir
    --with-png-dir
    --with-freetype-dir
    --enable-gd-native-ttf
    --with-gettext
    --with-imap
    --with-imap-ssl
    --with-kerberos
    --enable-bcmath
    --enable-mbstring
    --with-mcrypt
    --with-mysqli
    --with-pdo-mysql
    --enable-shmop
    --enable-soap
    --enable-sockets
    --with-xmlrpc
    --with-xsl
    --enable-zip
    --with-iconv-dir
    --with-pear
    --enable-intl
    --enable-opcache
    --enable-pcntl
    chdir=/tmp/php-{{ php_version }}

- name: Make
  shell: make > /dev/null chdir=/tmp/php-{{ php_version }}

- name: Install
  shell: make install > /dev/null chdir=/tmp/php-{{ php_version }}
  become: yes

- name: Create /etc/php5/cli/conf.d
  file: path=/etc/php5/cli/conf.d state=directory mode=0755 recurse=yes
  become: yes

- name: Create php.ini
  copy: force=no src=php.ini dest=/etc/php5/cli/php.ini
  become: yes
