---

- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - make
    - gcc
    - g++
    - libicu-dev
    - libssl-dev
    - libxml2-dev
    - libcurl4-openssl-dev
    - libjpeg-dev
    - libvpx-dev
    - libpng12-dev
    - libfreetype6-dev
    - libc-client2007e-dev
    - libkrb5-dev
    - libmcrypt-dev
    - libxslt1-dev
    - libbz2-dev
    - automake
    - autoconf
    - pkg-config
  become: yes

- name: Fetch .deb
  get_url: url=https://ftp.weheartwebsites.de/debian/jessie/php5-cli_{{ php_version }}_amd64.deb dest=/tmp/php5-cli_{{ php_version }}_amd64.deb

- name: Install .deb
  apt: deb=/tmp/php5-cli_{{ php_version }}_amd64.deb
  become: yes

- name: Create /etc/php5/cli/conf.d
  file: path=/etc/php5/cli/conf.d state=directory mode=0755 recurse=yes
  become: yes

- name: Create php.ini
  copy: src=php.ini dest=/etc/php5/cli/php.ini mode=0644
  become: yes
